export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAILURE = 'LOGIN_USER_FAILURE';
export const LOGIN_USER_REQUEST = 'LOGIN_USER_REQUEST';
export const LOGOUT_USER = 'LOGOUT_USER';

export const RETRIEVE_USER_SOCIETY = 'RETRIEVE_USER_SOCIETY';
export const RETRIEVE_USER_EVENT = 'RETRIEVE_USER_EVENT';

export const RETRIEVE_SOCIETIES = 'RETRIEVE_SOCIETIES';
export const RETRIEVE_EVENTS = 'RETRIEVE_EVENTS';

export const RETRIEVE_S_NEWSFEED = 'RETRIEVE_NEWSFEED';

export const CREATE_SOCIETY = 'CREATE_SOCIETY';
export const CREATE_EVENT = 'CREATE_EVENT';

export const FETCH_PROTECTED_DATA_REQUEST = 'FETCH_PROTECTED_DATA_REQUEST';
export const RECEIVE_PROTECTED_DATA = 'RECEIVE_PROTECTED_DATA';