export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAILURE = 'LOGIN_USER_FAILURE';
export const LOGIN_USER_REQUEST = 'LOGIN_USER_REQUEST';
export const LOGOUT_USER = 'LOGOUT_USER';
export const GET_FCM_TOKEN = 'GET_FCM_TOKEN';

export const UPDATE_RETRIEVE_LOADINGBAR = 'UPDATE_RETRIEVE_LOADINGBAR';
export const UPDATE_POST_LOADINGBAR = 'UPDATE_POST_LOADINGBAR';
export const UPDATE_AUTH_LOADINGBAR = 'UPDATE_AUTH_LOADINGBAR';
export const UPDATE_DELETE_LOADINGBAR = 'UPDATE_DELETE_LOADINGBAR';

export const RETRIEVE_ONE_SOCIETY = 'RETRIEVE_ONE_SOCIETY';
export const RETRIEVE_ONE_EVENT = 'RETRIEVE_ONE_EVENT';
export const RETRIEVE_ONE_SOCIETY_EVENTS = 'RETRIEVE_ONE_SOCIETY_EVENTS';
export const RETRIEVE_ONE_EVENT_CREW = 'RETRIEVE_ONE_EVENT_CREW';
export const RETRIEVE_COMM = 'RETRIEVE_COMM';
export const RETRIEVE_PARTICIPANT = 'RETRIEVE_PARTICIPANT';
export const RETRIEVE_USER_EVENTS = 'RETRIEVE_USER_EVENTS';
export const RETRIEVE_CREW_POSITION = 'RETRIEVE_CREW_POSITION';

export const RETRIEVE_SOCIETIES = 'RETRIEVE_SOCIETIES';
export const RETRIEVE_EVENTS = 'RETRIEVE_EVENTS';
export const RETRIEVE_ALL_SOCIETY_EVENTS = 'RETRIEVE_SOCIETY_EVENTS';
export const RETRIEVE_SOCIETY_BOOTHS = 'RETRIEVE_SOCIETY_BOOTHS';
export const RETRIEVE_EVENT_BOOTHS = 'RETRIEVE_EVENT_BOOTHS';
export const RETRIEVE_ALL_BOOTHS = 'RETRIEVE_ALL_BOOTHS';
export const RETRIEVE_SOCIETY_MEMBERS = 'RETRIEVE_SOCIETY_MEMBERS';
export const RETRIEVE_NEWSFEED = 'RETRIEVE_NEWSFEED';
export const RETRIEVE_BOOTH_AMOUNT = 'RETRIEVE_BOOTH_AMOUNT';

export const CREATE = 'CREATE';
// export const CREATE_SOCIETY = 'CREATE_SOCIETY';
// export const CREATE_EVENT = 'CREATE_EVENT';
// export const CREATE_NEWSFEED = 'CREATE_NEWSFEED';
// export const CREATE_RATING = 'CREATE_RATING';

export const REGISTER = 'REGISTER';
// export const REGISTER_SOCIETY = 'REGISTER_SOCIETY';
// export const REGISTER_EVENT = 'REGISTER_EVENT';
// export const REGISTER_CREW = 'REGISTER_CREW';
// export const REGISTER_BOOTH = 'REGISTER_BOOTH';

export const UPDATE = 'UPDATE';
// export const UPDATE_SOCIETY = 'UPDATE_SOCIETY';
// export const UPDATE_EVENT = 'UPDATE_EVENT';

export const FETCH_PROTECTED_DATA_REQUEST = 'FETCH_PROTECTED_DATA_REQUEST';
export const RECEIVE_PROTECTED_DATA = 'RECEIVE_PROTECTED_DATA';

export const CHECK_IS_REGISTERED = 'CHECK_IS_REGISTERED';

export const SEARCH_SOCIETY = 'SEARCH_SOCIETY';
export const SEARCH_EVENT = 'SEARCH_EVENT';

export const DELETE_PARTICIPATION = 'DELETE_PARTICIPATION';
export const DELETE_DATA = 'DELETE_DATA';